// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_KyZA09rCYGWMuGBenoySndGwvLLJhHw',
    appId: '1:972581025050:web:61e6bea24494ecea7a68a3',
    messagingSenderId: '972581025050',
    projectId: 'drago-trade-359db',
    authDomain: 'drago-trade-359db.firebaseapp.com',
    storageBucket: 'drago-trade-359db.appspot.com',
    measurementId: 'G-PSTYD98V92',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtVpls3yIII7nYXqwQY85KrjlP2NxIi48',
    appId: '1:972581025050:android:9f998f11ab26bf047a68a3',
    messagingSenderId: '972581025050',
    projectId: 'drago-trade-359db',
    storageBucket: 'drago-trade-359db.appspot.com',
  );
}
